### ISSUE TITLE
if always evaluates to True

### ISSUE THREAD

**Issue by paskino** [dkazanc/ToMoBAR#32]
I think [this](https://github.com/dkazanc/ToMoBAR/blob/master/src/Python/tomobar/methodsIR.py#L74) line always evaluates to `True` as a string cannot be `LS and PWLS` at the same time.

consider rewriting as
```python

if datafidelity not in ['LS','PWLS']:
    raise ValueError()
```

**Comment by paskino** [comment]
mmm, I'm wrong. Your code is correct, though the proposed change would make it more readable.

**Comment by dkazanc** [comment]
@edo agree, will change.

**Comment by dkazanc** [comment]
#38
