### ISSUE TITLE
reconstruct 3d point cloud from sinogram images

### ISSUE THREAD

**Issue by shalinsirwani** [dkazanc/ToMoBAR#36]
Is it possible to construct 3d point cloud from sinogram images...

**Comment by dkazanc** [comment]
sorry what do you mean exactly by 3d point cloud?

**Comment by shalinsirwani** [comment]
Actually I have 100 images of a object with interval of 3.60.
Now using opencv I achieved 576 sinograms ( of dimension 100 x 768 as images having dimension 576 x 768 ).
Now I want to generate 3d points cloud ( x y z coordinates)  from resultant sinograms.
If it is possible then how using this tool.?
If not , any suggestions.....

**Comment by dkazanc** [comment]
I guess if you backproject each of your detector-column in the sinogram you should get a pixel response in the reconstructed space. I'm not sure, however, what exactly you're trying to achieve. You can use simple filtered backprojection algorithm for reconstruction hence no specific need for TomoPhantom or Tomobar.

**Comment by shalinsirwani** [comment]
So if I use TomoPhantom what type of input and output have to give? ( If possible please provide sample for input and output) . 
What actually I want to confirm that the output must be 3d points.. that's it .

**Comment by dkazanc** [comment]
You can look at some demos [here](https://github.com/dkazanc/TomoPhantom/blob/master/Wrappers/Python/Demos/).

**Comment by shalinsirwani** [comment]
What if I want to provide custom input file ??

**Comment by dkazanc** [comment]
and what's inside this custom input file?

**Comment by shalinsirwani** [comment]
Might be images of object with different angles...

**Comment by dkazanc** [comment]
there is a certain syntax to follow if you use TomoPhantom. The software is for generation of phantoms and analytical projections. If you need reconstruction you might just as well use [ASTRA toolbox](http://www.astra-toolbox.com/). If you want to pass an input file then you need to write a converter for astra to work with.
