### ISSUE TITLE
enviornment.yml issue

### ISSUE THREAD

**Issue by aaron4444** [dkazanc/ToMoBAR#92]
Hi,
tried to install via the enviornment.yml.

dependencies:
  - httomo::ccpi-regularisation-cupy
  - **httomo**::ccpi-regulariser 

the regular ccpi-regulariser couldn't be installed on windows 11, using httomo channel, only ccpi channel.

its only a partial fix. I get the following errors when trying to do the tests so its not a complete fix. I haven't figured those out yet. 

FAILED tests/test_RecToolsDIRCuPy.py::test_Fourier_inv3D_performance - AssertionError: assert 'performance in ms' == 228.49582
FAILED tests/test_RecToolsDIRCuPy.py::test_FBP_performance - AssertionError: assert 'performance in ms' == 490.4246099999999
FAILED tests/test_RecToolsIR.py::test_FISTA_PWLS_OS_reg_2D - NameError: name 'PD_TV' is not defined
FAILED tests/test_RecToolsIR.py::test_FISTA_PWLS_OS_reg2_2D - NameError: name 'FGP_TV' is not defined
FAILED tests/test_RecToolsIR.py::test_ADMM2D - TypeError: gmres() got an unexpected keyword argument 'tol'
FAILED tests/test_RecToolsIR.py::test_ADMM3D - TypeError: gmres() got an unexpected keyword argument 'tol'
FAILED tests/test_RecToolsIR.py::test_ADMM3D_reg - TypeError: gmres() got an unexpected keyword argument 'tol'
FAILED tests/test_RecToolsIR.py::test_FISTA_OS_regul_3D - NameError: name 'PD_TV' is not defined
============================================ 8 failed, 58 passed in 27.20s ============================================

**Comment by dkazanc** [comment]
thanks @aaron4444. I'm trying to get this [PR](https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/pull/206/) merged into CCPi-Regularisation Toolkit. As some changes in the toolkit introduced backward incompatibility, there are also changes needed in ToMoBAR. I'll try to resolve it soon-ish. Cheers

**Comment by dkazanc** [comment]
the gmres error with respect to `tol  should be fixed now, let me know if it works for you.

**Comment by aaron4444** [comment]
Yes it works thank you!
