### ISSUE TITLE
pip install not working on clean conda env python 3.12

### ISSUE THREAD

**Issue by aaron4444** [dkazanc/ToMoBAR#93]
Hi, 

Tried the pip install method into a clean conda env with just python 3.12, but astra-toolbox is giving trouble it seems. 

  ERROR: Failed building wheel for astra-toolbox
  Running setup.py clean for astra-toolbox
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Aaron-Crucial-2016\AppData\Local\Temp\pip-install-i5dshklq\astra-toolbox_f948bbf8c77448019ca30c7ebdb1e3a2\setup.py", line 76, in <module>
          subprocess.call(['./autogen.sh'])
        File "C:\Users\Aaron-Crucial-2016\anaconda3\envs\tomobarA\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron-Crucial-2016\anaconda3\envs\tomobarA\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Aaron-Crucial-2016\anaconda3\envs\tomobarA\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: [WinError 193] %1 is not a valid Win32 application
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for astra-toolbox
Failed to build astra-toolbox
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (astra-toolbox)

**Comment by dkazanc** [comment]
Hi @aaron4444, I hope the issue is resolved now. Please check the updated [installation](https://dkazanc.github.io/ToMoBAR/howto/installation.html) page. I did quick testing on my Windows machine, everything seems to work using one line install: 
`conda install -c httomo -c conda-forge tomophantom tomobar astra-toolbox ccpi-regulariser `

Also I spent some time updating [API](https://dkazanc.github.io/ToMoBAR/reference/api.html) and docs in general. Hope it helps. thanks

**Comment by aaron4444** [comment]
Thank you for your careful attention to this, yes the new one line install works! I'll test the cupy part over the weekend. I'm checking the other enviornment.yml installation pathway as well.
